// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2IN44dix--bYZGuDf08hfIxLv-Df2M4',
    appId: '1:595004945233:web:a5ff46e58ac118d90cd970',
    messagingSenderId: '595004945233',
    projectId: 'attandance-debc1',
    authDomain: 'attandance-debc1.firebaseapp.com',
    storageBucket: 'attandance-debc1.appspot.com',
    measurementId: 'G-Q2FF03F6S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4ys4xqzAcx6AzmS8gjILBDtXnpygRfk',
    appId: '1:595004945233:android:518412fa94f469950cd970',
    messagingSenderId: '595004945233',
    projectId: 'attandance-debc1',
    storageBucket: 'attandance-debc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOw9MNcnKjOuBcGNYiMBREOG3G_coBX6E',
    appId: '1:595004945233:ios:689fec003edb179b0cd970',
    messagingSenderId: '595004945233',
    projectId: 'attandance-debc1',
    storageBucket: 'attandance-debc1.appspot.com',
    iosBundleId: 'com.example.internship1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOw9MNcnKjOuBcGNYiMBREOG3G_coBX6E',
    appId: '1:595004945233:ios:689fec003edb179b0cd970',
    messagingSenderId: '595004945233',
    projectId: 'attandance-debc1',
    storageBucket: 'attandance-debc1.appspot.com',
    iosBundleId: 'com.example.internship1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk2IN44dix--bYZGuDf08hfIxLv-Df2M4',
    appId: '1:595004945233:web:f296fa8fc26cfadd0cd970',
    messagingSenderId: '595004945233',
    projectId: 'attandance-debc1',
    authDomain: 'attandance-debc1.firebaseapp.com',
    storageBucket: 'attandance-debc1.appspot.com',
    measurementId: 'G-KZ3PGRXR6X',
  );

}